version: '3.7'

services:

  sample:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/src'
      - '/node_modules'
    ports:
      - 3001:3000
